# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: check-added-large-files
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: file-contents-sorter
        files: ^(\.gitignore|po/LINGUAS)$
    -   id: trailing-whitespace
        exclude: ^(ChangeLog-2013|patches/.*)$
        args: [--chars, " \t\n\r\v"]
-   repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v18.1.8
    hooks:
    -   id: clang-format
        exclude: ^lib/mp\.h$
-   repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
    -   id: shellcheck
        exclude: ^bootstrap$
-   repo: https://github.com/scop/pre-commit-perlcritic
    rev: v1.152-1
    hooks:
    -   id: perlcritic
        args: [--stern]
