# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: check-added-large-files
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
        exclude: ^(ChangeLog-2013|patches/.*)$
        args: [--chars, " \t\n\r\v"]
-   repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.8.0.4
    hooks:
    -   id: shellcheck
        alias: shellcheck-tools
        exclude: ^(bootstrap|src/tests/.*)$
    -   id: shellcheck
        alias: shellcheck-tests
        name: shellcheck (src/tests/)
        files: ^src/tests/.*$
        args: ["-P", "src/tests"]
